services:
    liker_event_log:
        build:
            context: .
            dockerfile: Dockerfile
        command: sleep infinity
        volumes:
            - ./:/workspace
        networks:
            - liker_external_network
            - liker_event_log_internal_network
    db:
        networks:
            - liker_event_log_internal_network
    adminer:
        image: adminer
        depends_on:
            - db
        restart: always
        ports:
            - ${LIKER_EVENT_LOG_ADMINER_HOST_PORT}:8080
        networks:
            - liker_event_log_internal_network
networks:
    liker_external_network:
        external: true
        name: "liker"
    liker_event_log_internal_network:
        external: false
        name: "liker_event_log_internal_network"
